nextbi:
  profile: dev
  ip: ${nextbi.profile}.one.nextbi.ru
  redis: # потом удалить, когда все у себя удалят
    host: 192.168.5.21
    port: 6379
  database:
    ip: 192.168.50.115 # IP адрес БД PostgreSQL
    username: postgres
    password: 123456
  rabbitmq:
#    ip: ${nextbi.ip} # IP адрес RabbitMQ
    ip: localhost # IP адрес RabbitMQ
    password: ${spring.application.name} # общий пароль для всех модулей
  logback:
    ip: ${nextbi.ip}
    level: INFO
  message: # TODO удалить и использовать nextbi.antifraud.rabbit.message
    path:
      NONE: antifraud_enrichment-service
      ADAK_DONE: antifraud_enrichment-service
      ENRICHED: antifraud_scoring-service
      RDAK_REQUIRED: antifraud_workstation-service
      ADAK_REQUIRED: antifraud_transaction-gate-service
      R_PROCCESSED: antifraud_ml-service
      APPROVED: antifraud_scoring-service
      REFUSED: antifraud_scoring-service
      NO_DATA: antifraud_scoring-service
      WORKFLOW_DONE: exit_gate-servicи
  security:
    address-infrastructure: /actuator/** #через запятую без пробелов, инфраструктурные апи, на которые не нужна авторизация, не должно включать в себя /api/**
    forbidden-to-edit-menu: # объекты(функции и сервисы, одновременно меню), на которые захардкожена возможность иметь права только группе SUPERVISOR
      client-service:
        service-object-uuid: 80619f69-ea03-4b7e-a274-ae4d605b5038
        settings-object-uuid: 0d52fa26-4607-48b2-803c-4b83acabbc70
      auth-service:
        service-object-uuid: 6e1056fd-c86a-4a84-a99a-faf865109c13
        users-uuid: 1474942e-85c7-11e8-adc0-fa7ae01bbebc
        groups-uuid: 1474979e-85c7-11e8-adc0-fa7ae01bbebc
        menu-items: a9a38794-9be8-11e8-98d0-529269fb1459
      total: ${nextbi.security.forbidden-to-edit-menu.client-service.service-object-uuid},${nextbi.security.forbidden-to-edit-menu.client-service.settings-object-uuid},${nextbi.security.forbidden-to-edit-menu.auth-service.service-object-uuid},${nextbi.security.forbidden-to-edit-menu.auth-service.users-uuid},${nextbi.security.forbidden-to-edit-menu.auth-service.groups-uuid},${nextbi.security.forbidden-to-edit-menu.auth-service.menu-items}
    eureka: # потом удалить и переделать на system-auth в конфигах модулей
      user: discUser
      password: discPassword
    main-object-uuid: 147b233e-449a-11e8-842f-0ed5f89f718b
    supervisor-login: supervisor
    system-auth:
      user: discUser
      password: discPassword
  antifraud:
    datasource:
        url: jdbc:postgresql://${nextbi.database.ip:localhost}:5432/${nextbi.profile}_import_data
        username: postgres
        password: 123456
        driver-class-name: org.postgresql.Driver
        schema: test_bank_schema
    rabbit:
        message:
            path:
              NONE: antifraud_enrichment-service
              ADAK_DONE: antifraud_enrichment-service
              ENRICHED: antifraud_scoring-service
              RDAK_REQUIRED: antifraud_workstation-service
              ADAK_REQUIRED: antifraud_transaction-gate-service
              R_PROCCESSED: antifraud_ml-service
              APPROVED: antifraud_scoring-service
              REFUSED: antifraud_scoring-service
              NO_DATA: antifraud_scoring-service
              WORKFLOW_DONE: antifraud_exit-gate-service
    ignite:
        mode: multicast # vm или multicast
        client: true
        vm:
            addresses: 127.0.0.1
        multicast:
            group: 228.1.2.1
            port: 47401
        data-storage:
            enabled: false
        backup: 1 # кол-во нод, на которые должны реплицироваться данные

spring:
  jackson:
    time-zone: Europe/Moscow
  redis:
    host: 192.168.5.21
    port: 6379
    password: TestPassword
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  cloud:
#    config:
#      override-none: true # разрешение на переопределение данной конфигурации локальной
    stream:
      default:
        contentType: application/json
      bindings:
        antifraud_input:
          group: input
          destination: antifraud_${spring.application.name}
          binder: rabbit_notification
#        antifraud_output:
#          binder: rabbit_notification
        notification_output:
          destination: ${spring.application.name}
          binder: rabbit_notification
        mail_input:
          group: input
          destination: mail-service
          binder: rabbit_notification
        mail_output:
          group:
          destination: incoming-mail-and-delivery-reports
          binder: rabbit_notification
        right_to_object_input:
          group:
          destination: caching-info-about-access-objects
          binder: rabbit_notification
        access_objects_output:
          consumer:
            concurrency: 2 # пример активации многопоточной обработки
          group: input
          destination: auth-service
          binder: rabbit_notification
        springCloudBusInput:
          destination: springCloudBus
          binder: rabbit_notification
#      rabbit:
#        bindings:
#          antifraud_output:
#            producer:
#              declareExchange: false
      binders:
        rabbit_notification:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: ${nextbi.rabbitmq.ip}
                port: 5672
                virtual-host: vh_notification
                username: ${spring.application.name}
                password: ${nextbi.rabbitmq.password}
      default-binder: rabbit_notification
    refresh:
      extra-refreshable:
      - javax.sql.DataSource
  rabbitmq: # для актуатора
    host: ${nextbi.rabbitmq.ip:localhost}
    port: 5672
    virtual-host: vh_notification
    username: ${spring.application.name}
    password: ${nextbi.rabbitmq.password}

eureka:
  client:
    service-url:
      defaultZone: http://${nextbi.security.system-auth.user}:${nextbi.security.system-auth.password}@${org.one.nextbi.zonehost:localhost}:8761/eureka/
#      defaultZone: http://${nextbi.security.system-auth.user}:${nextbi.security.system-auth.password}@${org.one.nextbi.zonehost}:8761/eureka/
  instance:
    prefer-ip-address: true
