spring:
  cloud:
    config:
      overrideNone: true

nextbi:
  caching-service:
    async:
      cores: 2 # пул ядер
    init:
      start-on-startup: true #инициализировать кэш на старте
      data-period: 30 #период в днях за который должны быть закэшированы данные содержащие временную метку (например, транзакции). время жизни таких данных от момента создания будет равно выбранному значению
    update:
      import-notification: #параметры обновления кэша при обработке оповещения от сервиса импорта
        schema: test_bank_schema #имя схемы, оповещения об овновлении которой должны быть обработаны
        buffered: false #буферезировать данные перед обновлением
#        buffer-size-map: #размер буфера для каждой сущности, например, transaction: 100