nextbi:
  mail-service:
    mail: # конфигурация для приема сообщений
      sender-address: robot2@nextbi.ru
      receiver:
        config: classpath:/mail-imap-idle-config.xml
        auth: imaps://robot2:9jGng9wMiZ@mail.nextbi.ru:993/inbox
#        config: classpath:/mail-pop3-config.xml
#        auth: pop3://robot2:9jGng9wMiZ@pop.nextbi.ru/INBOX
        should-delete-messages: false
        should-mark-messages-as-read: false
        auto-startup: false   # ИЗМЕНИТЬ ДЛЯ ВКЛЮЧЕНИЯ ПРИЕМА СООБЩЕНИЙ
        debug: false
        imap:
          socketFactory:
            fallback: false
        pop3:
          port: 110
          socketFactory:
            port: 110
            fallback: false

server:
  port: 8091
spring:
  mail: # конфигурация для отправки сообщений
    host: mail.nextbi.ru
    port: 465
    username: robot2
    password: 9jGng9wMiZ
    properties:
      mail:
        smtp:
          ssl:
            enable: true
            trust: mail.nextbi.ru
eureka:
  instance:
    metadata-map:
      NEXTBI_NAME: Модуль почтового обмена
