nextbi:
  mail-service:
    mail: # конфигурация для приема сообщений
      sender-address: robot2@nextbi.ru
      receiver:
        config: classpath:/mail-imap-idle-config.xml
#        config: classpath:/mail-pop3-config.xml

server:
  port: 8091
spring:
  mail: # конфигурация для отправки сообщений
    host: mail.nextbi.ru
    port: 465
    username: robot2
    password: 9jGng9wMiZ
    properties:
      mail:
        smtp:
          ssl:
            enable: true
            trust: mail.nextbi.ru
eureka:
  instance:
    metadata-map:
      NEXTBI_NAME: Модуль почтового обмена
